=== vkmanojk/NetCentricProgramming/XML/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="student">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="firstName" type="xsd:string"/>
			<xsd:element name="lastName" type="xsd:string"/>
			<xsd:element name="id" type="xsd:ID"/>
			<xsd:element ref="plan"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
<xsd:element name="record">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="grade" type="xsd:string"/>
			<xsd:element name="date" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
<xsd:element name="course">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="shortName" type="xsd:string"/>
			<xsd:element ref="record" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
<xsd:element name="courses">
	<xsd:complexType>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="course"/>
		</xsd:sequence>
		<xsd:attribute name="year" type="xsd:string"/>
	</xsd:complexType>
</xsd:element>
<xsd:element name="plan">
	<xsd:complexType>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="courses"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:unique name="coursesYear">
		<xsd:selector xpath="courses"/>
		<xsd:field xpath="@year"/>
	</xsd:unique>
</xsd:element>

=== vkmanojk/NetCentricProgramming/XML/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='student.xsd'>
	<firstName>Luca</firstName>
	<lastName>Rossi</lastName>
	<id>281283</id>
	<plan>
		<courses year="3">
			<course>
				<name> Programmazione Orientata agli Oggetti </name>
				<shortName>POO</shortName>
				<record>
					<grade>30</grade>
					<date>13/06/11</date>
				</record>
			</course>
			<course>
				<name>Analisi e progettazione del software</name>
				<shortName>APS</shortName>
			</course>
		</courses>
	</plan>
</student>
